=== Martincres4/LenguajeDeMarcas/PracticaResuelta3Ev/Ejercicio2_XSD/XSDCompeticion.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="FormulaX" type="tFormulaX" />
	<xs:complexType name="tFormulaX">
		<xs:sequence>
			<xs:element name="Escuderias" type="tEscuderias" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tEscuderias">
		<xs:sequence>
			<xs:element name="Escuderia" type="tEscuderia" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tEscuderia">
		<xs:all>
			<xs:element name="JefeEscuderia" type="tJefeEscuderia" minOccurs="1" maxOccurs="1" />
			<xs:element name="Mecanico1" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="Mecanico2" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="Piloto1" type="tPiloto" minOccurs="1" maxOccurs="1" />
			<xs:element name="Piloto2" type="tPiloto" minOccurs="0" maxOccurs="1" />
			<xs:element name="Coche" type="tCoche" minOccurs="1" maxOccurs="1" />
			<xs:element name="Fundacion" type="tFundacion" minOccurs="1" maxOccurs="1" />
		</xs:all>
		<xs:attribute name="NomEscu" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="tJefeEscuderia">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="Antiguedad" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="tPiloto">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="Titular" type="tTitular" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="tCoche">
		<xs:sequence>
			<xs:element name="VelocidadMax" type="tVeloMax" minOccurs="1" maxOccurs="1" />
			<xs:element name="Aceleracion" type="tAceleracion" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tFundacion">
		<xs:choice>
			<xs:element name="FechaFundacion" type="xs:date" />
			<xs:element name="AnoFundacion" type="xs:string" />
		</xs:choice>
	</xs:complexType>

	<xs:simpleType name="tTitular">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Si" />
			<xs:enumeration value="No" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tVeloMax">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{3}(.)[0-9]{2,3}( )(km/h)" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tAceleracion">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{2,4}(,)[0-9]{2}( )(m/s2|cm/s2)" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== Martincres4/LenguajeDeMarcas/PracticaResuelta3Ev/Ejercicio2_XSD/Competicion_XML_XSD.xml
<?xml version ="1.0" encoding ="UTF-8"?>
<FormulaX xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSDCompeticion.xsd">
  <Escuderias>
	<Escuderia NomEscu="Rayo Veloz">
		<JefeEscuderia Antiguedad="2 ano">Carlos Escobar Azalea</JefeEscuderia>
		<Mecanico1>Sergio Pinilla Lima</Mecanico1>
		<Mecanico2>David Zaragoza Luarca</Mecanico2>
		<Piloto1 Titular="Si">Guillermo Formoza Carrillo</Piloto1>
		<Piloto2 Titular="No">Nuria Calvo Sopera</Piloto2>
		<Coche>
			<VelocidadMax>357.432 km/h</VelocidadMax>
			<Aceleracion>14,78 m/s2</Aceleracion>
		</Coche>
		<Fundacion>
			<FechaFundacion>2020-11-13</FechaFundacion>
		</Fundacion>
	</Escuderia>
	<Escuderia NomEscu="FSpeed">
		<Mecanico1>Lilian Welcome Ferdinand</Mecanico1>
		<JefeEscuderia Antiguedad="13 ano">John Fouler Smith</JefeEscuderia>
		<Fundacion>
			<AnoFundacion>2001</AnoFundacion>
		</Fundacion>
		<Piloto2 Titular="No">Charles Chester Durnet</Piloto2>
		<Piloto1 Titular="Si">Charlotte Gyle Clarence</Piloto1>
		<Coche>
			<VelocidadMax>361.01 km/h</VelocidadMax>	
		</Coche>
	</Escuderia>
	<Escuderia NomEscu="Hypercars">
		<Mecanico1>Hasen Vickers Traore</Mecanico1>
		<Coche>
			<VelocidadMax>365.689 km/h</VelocidadMax>
			<Aceleracion>1545,00 cm/s2</Aceleracion>	
		</Coche>
		<JefeEscuderia Antiguedad="5 ano">Ricard Perkin Gringou</JefeEscuderia>
		<Piloto1 Titular="Si">Frederick Lemarc Anglue</Piloto1>
		<Fundacion>
			<FechaFundacion>2014-07-05</FechaFundacion>
		</Fundacion>
	</Escuderia>
	<Escuderia NomEscu="FAutomobile">
		<JefeEscuderia Antiguedad="8 ano">Francesco Bianchi Zanella</JefeEscuderia>
		<Mecanico2>Paolo Mecanio Baresi</Mecanico2>
		<Mecanico1>Fabio Napolitano Parotta</Mecanico1>
		<Piloto1 Titular="Si">Fabrizio Pesotto Fiorino</Piloto1>
		<Coche>
			<VelocidadMax>359.721 km/h</VelocidadMax>
		</Coche>
		<Fundacion>
			<FechaFundacion>2011-09-14</FechaFundacion>
		</Fundacion>
	</Escuderia>
   </Escuderias>

</FormulaX>
